"""Add secret_id to Role model

Revision ID: 74562ed36cfa
Revises: 12b6c4a5a52b
Create Date: 2023-11-26 23:24:48.642226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74562ed36cfa'
down_revision = '12b6c4a5a52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role') as batch_op:
        batch_op.add_column(sa.Column('secret_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('role') as batch_op:
        batch_op.create_unique_constraint('uq_secret_id', ['secret_id'])

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secret_id')

    op.create_table('user_role',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###
